import { Product, Category, User, Table, Order } from '../types';

export const seedData = {
  categories: [
    { id: 'cat-1', name: 'Hamburguesas', icon: '🍔', type: 'cocina' as const, order: 1 },
    { id: 'cat-2', name: 'Tacos', icon: '🌮', type: 'cocina' as const, order: 2 },
    { id: 'cat-3', name: 'Alitas', icon: '🍗', type: 'cocina' as const, order: 3 },
    { id: 'cat-4', name: 'Ensaladas', icon: '🥗', type: 'cocina' as const, order: 4 },
    { id: 'cat-5', name: 'Cocteles', icon: '🍹', type: 'bebida' as const, order: 5 },
    { id: 'cat-6', name: 'Cervezas', icon: '🍺', type: 'bebida' as const, order: 6 },
    { id: 'cat-7', name: 'Refrescos', icon: '🥤', type: 'bebida' as const, order: 7 },
    { id: 'cat-8', name: 'Postres', icon: '🍰', type: 'cocina' as const, order: 8 },
  ] as Category[],

  products: [
    {
      id: 'prod-1',
      name: 'Hamburguesa Clásica',
      price: 120,
      type: 'cocina' as const,
      category: 'cat-1',
      active: true,
      createdAt: new Date().toISOString(),
      configs: [
        {
          id: 'cfg-1-1',
          name: 'Ingredientes',
          order: 1,
          options: [
            { id: 'opt-1-1-1', name: 'Lechuga', extraPrice: 0, isDefault: true, order: 1 },
            { id: 'opt-1-1-2', name: 'Jitomate', extraPrice: 0, isDefault: true, order: 2 },
            { id: 'opt-1-1-3', name: 'Cebolla', extraPrice: 0, isDefault: true, order: 3 },
            { id: 'opt-1-1-4', name: 'Pepinillos', extraPrice: 0, isDefault: false, order: 4 },
            { id: 'opt-1-1-5', name: 'Jalapeño', extraPrice: 0, isDefault: false, order: 5 },
          ],
        },
        {
          id: 'cfg-1-2',
          name: 'Queso',
          order: 2,
          options: [
            { id: 'opt-1-2-1', name: 'Americano', extraPrice: 0, isDefault: true, order: 1 },
            { id: 'opt-1-2-2', name: 'Cheddar', extraPrice: 10, isDefault: false, order: 2 },
            { id: 'opt-1-2-3', name: 'Suizo', extraPrice: 15, isDefault: false, order: 3 },
            { id: 'opt-1-2-4', name: 'Sin queso', extraPrice: 0, isDefault: false, order: 4 },
          ],
        },
        {
          id: 'cfg-1-3',
          name: 'Extras',
          order: 3,
          options: [
            { id: 'opt-1-3-1', name: 'Tocino', extraPrice: 25, isDefault: false, order: 1 },
            { id: 'opt-1-3-2', name: 'Aguacate', extraPrice: 20, isDefault: false, order: 2 },
            { id: 'opt-1-3-3', name: 'Huevo', extraPrice: 15, isDefault: false, order: 3 },
            { id: 'opt-1-3-4', name: 'Doble carne', extraPrice: 45, isDefault: false, order: 4 },
          ],
        },
      ],
    },
    {
      id: 'prod-2',
      name: 'Hamburguesa BBQ',
      price: 145,
      type: 'cocina' as const,
      category: 'cat-1',
      active: true,
      createdAt: new Date().toISOString(),
      configs: [
        {
          id: 'cfg-2-1',
          name: 'Ingredientes',
          order: 1,
          options: [
            { id: 'opt-2-1-1', name: 'Lechuga', extraPrice: 0, isDefault: true, order: 1 },
            { id: 'opt-2-1-2', name: 'Cebolla caramelizada', extraPrice: 0, isDefault: true, order: 2 },
            { id: 'opt-2-1-3', name: 'Aros de cebolla', extraPrice: 0, isDefault: true, order: 3 },
            { id: 'opt-2-1-4', name: 'Jalapeño', extraPrice: 0, isDefault: false, order: 4 },
          ],
        },
        {
          id: 'cfg-2-2',
          name: 'Extras',
          order: 2,
          options: [
            { id: 'opt-2-2-1', name: 'Tocino', extraPrice: 25, isDefault: true, order: 1 },
            { id: 'opt-2-2-2', name: 'Doble carne', extraPrice: 45, isDefault: false, order: 2 },
          ],
        },
      ],
    },
    {
      id: 'prod-3',
      name: 'Tacos al Pastor',
      price: 75,
      type: 'cocina' as const,
      category: 'cat-2',
      active: true,
      createdAt: new Date().toISOString(),
      configs: [
        {
          id: 'cfg-3-1',
          name: 'Ingredientes',
          order: 1,
          options: [
            { id: 'opt-3-1-1', name: 'Cilantro', extraPrice: 0, isDefault: true, order: 1 },
            { id: 'opt-3-1-2', name: 'Cebolla', extraPrice: 0, isDefault: true, order: 2 },
            { id: 'opt-3-1-3', name: 'Piña', extraPrice: 0, isDefault: true, order: 3 },
            { id: 'opt-3-1-4', name: 'Limón', extraPrice: 0, isDefault: false, order: 4 },
          ],
        },
        {
          id: 'cfg-3-2',
          name: 'Salsa',
          order: 2,
          options: [
            { id: 'opt-3-2-1', name: 'Verde', extraPrice: 0, isDefault: true, order: 1 },
            { id: 'opt-3-2-2', name: 'Roja', extraPrice: 0, isDefault: false, order: 2 },
            { id: 'opt-3-2-3', name: 'Habanero', extraPrice: 0, isDefault: false, order: 3 },
            { id: 'opt-3-2-4', name: 'Sin salsa', extraPrice: 0, isDefault: false, order: 4 },
          ],
        },
      ],
    },
    {
      id: 'prod-4',
      name: 'Tacos de Bistec',
      price: 85,
      type: 'cocina' as const,
      category: 'cat-2',
      active: true,
      createdAt: new Date().toISOString(),
      configs: [
        {
          id: 'cfg-4-1',
          name: 'Ingredientes',
          order: 1,
          options: [
            { id: 'opt-4-1-1', name: 'Cilantro', extraPrice: 0, isDefault: true, order: 1 },
            { id: 'opt-4-1-2', name: 'Cebolla', extraPrice: 0, isDefault: true, order: 2 },
            { id: 'opt-4-1-3', name: 'Guacamole', extraPrice: 15, isDefault: false, order: 3 },
          ],
        },
      ],
    },
    {
      id: 'prod-5',
      name: 'Alitas BBQ',
      price: 140,
      type: 'cocina' as const,
      category: 'cat-3',
      active: true,
      createdAt: new Date().toISOString(),
      configs: [
        {
          id: 'cfg-5-1',
          name: 'Salsa',
          order: 1,
          options: [
            { id: 'opt-5-1-1', name: 'BBQ', extraPrice: 0, isDefault: true, order: 1 },
            { id: 'opt-5-1-2', name: 'Buffalo', extraPrice: 0, isDefault: false, order: 2 },
            { id: 'opt-5-1-3', name: 'Mango habanero', extraPrice: 0, isDefault: false, order: 3 },
            { id: 'opt-5-1-4', name: 'Chipotle', extraPrice: 0, isDefault: false, order: 4 },
          ],
        },
        {
          id: 'cfg-5-2',
          name: 'Extras',
          order: 2,
          options: [
            { id: 'opt-5-2-1', name: 'Aderezo ranch', extraPrice: 10, isDefault: true, order: 1 },
            { id: 'opt-5-2-2', name: 'Papas fritas', extraPrice: 30, isDefault: false, order: 2 },
          ],
        },
      ],
    },
    {
      id: 'prod-6',
      name: 'Ensalada César',
      price: 95,
      type: 'cocina' as const,
      category: 'cat-4',
      active: true,
      createdAt: new Date().toISOString(),
      configs: [
        {
          id: 'cfg-6-1',
          name: 'Proteína',
          order: 1,
          options: [
            { id: 'opt-6-1-1', name: 'Pollo grillado', extraPrice: 0, isDefault: true, order: 1 },
            { id: 'opt-6-1-2', name: 'Camarón', extraPrice: 35, isDefault: false, order: 2 },
            { id: 'opt-6-1-3', name: 'Sin proteína', extraPrice: 0, isDefault: false, order: 3 },
          ],
        },
      ],
    },
    {
      id: 'prod-7',
      name: 'Margarita',
      price: 110,
      type: 'bebida' as const,
      category: 'cat-5',
      active: true,
      createdAt: new Date().toISOString(),
      configs: [
        {
          id: 'cfg-7-1',
          name: 'Sabor',
          order: 1,
          options: [
            { id: 'opt-7-1-1', name: 'Natural', extraPrice: 0, isDefault: true, order: 1 },
            { id: 'opt-7-1-2', name: 'Fresa', extraPrice: 10, isDefault: false, order: 2 },
            { id: 'opt-7-1-3', name: 'Mango', extraPrice: 10, isDefault: false, order: 3 },
            { id: 'opt-7-1-4', name: 'Tamarindo', extraPrice: 10, isDefault: false, order: 4 },
          ],
        },
        {
          id: 'cfg-7-2',
          name: 'Escarchado',
          order: 2,
          appliesTo: 'bebida' as const,
          options: [
            { id: 'opt-7-2-1', name: 'Sal', extraPrice: 0, isDefault: true, order: 1 },
            { id: 'opt-7-2-2', name: 'Chile', extraPrice: 0, isDefault: false, order: 2 },
            { id: 'opt-7-2-3', name: 'Chamoy', extraPrice: 5, isDefault: false, order: 3 },
            { id: 'opt-7-2-4', name: 'Sin escarchado', extraPrice: 0, isDefault: false, order: 4 },
          ],
        },
      ],
    },
    {
      id: 'prod-8',
      name: 'Michelada',
      price: 90,
      type: 'bebida' as const,
      category: 'cat-5',
      active: true,
      createdAt: new Date().toISOString(),
      configs: [
        {
          id: 'cfg-8-1',
          name: 'Estilo',
          order: 1,
          options: [
            { id: 'opt-8-1-1', name: 'Clásica', extraPrice: 0, isDefault: true, order: 1 },
            { id: 'opt-8-1-2', name: 'Cubana', extraPrice: 15, isDefault: false, order: 2 },
            { id: 'opt-8-1-3', name: 'Ojo rojo', extraPrice: 10, isDefault: false, order: 3 },
          ],
        },
        {
          id: 'cfg-8-2',
          name: 'Escarchado',
          order: 2,
          appliesTo: 'bebida' as const,
          options: [
            { id: 'opt-8-2-1', name: 'Chile-limón', extraPrice: 0, isDefault: true, order: 1 },
            { id: 'opt-8-2-2', name: 'Chamoy', extraPrice: 5, isDefault: false, order: 2 },
            { id: 'opt-8-2-3', name: 'Tajín', extraPrice: 0, isDefault: false, order: 3 },
          ],
        },
      ],
    },
    {
      id: 'prod-9',
      name: 'Corona Extra',
      price: 45,
      type: 'bebida' as const,
      category: 'cat-6',
      active: true,
      createdAt: new Date().toISOString(),
      configs: [],
    },
    {
      id: 'prod-10',
      name: 'Modelo Especial',
      price: 45,
      type: 'bebida' as const,
      category: 'cat-6',
      active: true,
      createdAt: new Date().toISOString(),
      configs: [],
    },
    {
      id: 'prod-11',
      name: 'Coca-Cola',
      price: 35,
      type: 'bebida' as const,
      category: 'cat-7',
      active: true,
      createdAt: new Date().toISOString(),
      configs: [],
    },
    {
      id: 'prod-12',
      name: 'Pastel de Chocolate',
      price: 75,
      type: 'cocina' as const,
      category: 'cat-8',
      active: true,
      createdAt: new Date().toISOString(),
      configs: [
        {
          id: 'cfg-12-1',
          name: 'Topping',
          order: 1,
          options: [
            { id: 'opt-12-1-1', name: 'Helado de vainilla', extraPrice: 20, isDefault: true, order: 1 },
            { id: 'opt-12-1-2', name: 'Crema batida', extraPrice: 10, isDefault: false, order: 2 },
            { id: 'opt-12-1-3', name: 'Sin topping', extraPrice: 0, isDefault: false, order: 3 },
          ],
        },
      ],
    },
  ] as Product[],

  users: [
    {
      id: 'user-1',
      name: 'Carlos Admin',
      email: 'carlos@resto.mx',
      pin: '1234',
      role: 'admin' as const,
      active: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: 'user-2',
      name: 'María Mesera',
      email: 'maria@resto.mx',
      pin: '5678',
      role: 'mesero' as const,
      active: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: 'user-3',
      name: 'Pedro Cocina',
      email: 'pedro@resto.mx',
      pin: '9012',
      role: 'cocina' as const,
      active: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: 'user-4',
      name: 'Ana Barra',
      email: 'ana@resto.mx',
      pin: '3456',
      role: 'barra' as const,
      active: true,
      createdAt: new Date().toISOString(),
    },
  ] as User[],

  tables: [
    { id: 'table-1', name: 'Mesa 1', capacity: 4, status: 'disponible' as const, zone: 'Interior' },
    { id: 'table-2', name: 'Mesa 2', capacity: 4, status: 'disponible' as const, zone: 'Interior' },
    { id: 'table-3', name: 'Mesa 3', capacity: 6, status: 'disponible' as const, zone: 'Interior' },
    { id: 'table-4', name: 'Mesa 4', capacity: 2, status: 'disponible' as const, zone: 'Interior' },
    { id: 'table-5', name: 'Mesa 5', capacity: 8, status: 'disponible' as const, zone: 'Terraza' },
    { id: 'table-6', name: 'Mesa 6', capacity: 4, status: 'disponible' as const, zone: 'Terraza' },
    { id: 'table-7', name: 'Mesa 7', capacity: 4, status: 'disponible' as const, zone: 'Terraza' },
    { id: 'table-8', name: 'Mesa 8', capacity: 6, status: 'disponible' as const, zone: 'Barra' },
    { id: 'table-9', name: 'Mesa 9', capacity: 2, status: 'disponible' as const, zone: 'Barra' },
    { id: 'table-10', name: 'Mesa 10', capacity: 10, status: 'disponible' as const, zone: 'Privado' },
  ] as Table[],

  orders: [] as Order[],

  inventory: [
    { id: 'inv-1', productId: 'prod-1', productName: 'Hamburguesa Clásica', stock: 50, minStock: 10, unit: 'piezas', lastUpdated: new Date().toISOString() },
    { id: 'inv-2', productId: 'prod-3', productName: 'Tacos al Pastor', stock: 80, minStock: 20, unit: 'piezas', lastUpdated: new Date().toISOString() },
    { id: 'inv-3', productId: 'prod-5', productName: 'Alitas BBQ', stock: 40, minStock: 10, unit: 'piezas', lastUpdated: new Date().toISOString() },
    { id: 'inv-4', productId: 'prod-9', productName: 'Corona Extra', stock: 120, minStock: 24, unit: 'botellas', lastUpdated: new Date().toISOString() },
    { id: 'inv-5', productId: 'prod-10', productName: 'Modelo Especial', stock: 96, minStock: 24, unit: 'botellas', lastUpdated: new Date().toISOString() },
    { id: 'inv-6', productId: 'prod-11', productName: 'Coca-Cola', stock: 200, minStock: 48, unit: 'latas', lastUpdated: new Date().toISOString() },
  ],
};
